version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing frontend dependencies..."
      - cd client
      - npm install
      - npm run build
      - cd ..

      - echo "Installing backend dependencies..."
      - cd server
      - npm install
      - cd ..

      - echo "Preparing deployment folder..."

      # Create necessary directories inside server
      - mkdir -p server/client
      - cp -r client/build server/client/

      # Copy deployment configs
      - cp appspec.yml server/
      - mkdir -p server/scripts
      - cp scripts/deploy.sh server/scripts/

build:
  commands:
    - echo "Build phase completed."

post_build:
  commands:
    - echo "Build and preparation completed. Ready for CodeDeploy."

artifacts:
  files:
    - '**/*'
  base-directory: server
