version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing client dependencies..."
      - cd client
      - npm install
      - npm run build
      - cd ..

      - echo "Installing server dependencies..."
      - cd server
      - npm install
      - cd ..

      - echo "Preparing deployment files..."
      - cp appspec.yml server/
      - mkdir -p server/scripts
      - cp scripts/deploy.sh server/scripts/

artifacts:
  files:
    - '**/*'
  base-directory: server
